openapi: 3.0.0
info:
  title: Investigation and Root Cause API
  version: 1.0.0
  description: API for fetching investigation questions and probable root causes based on provided inputs.

servers:
  - url: https://api.example.com

paths:
  /investigation_questions:
    get:
      summary: Get investigation questions based on event data
      description: This endpoint accepts event details and returns a list of investigation questions to assist with root cause analysis.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                event_description:
                  type: string
                  description: A brief description of the event (e.g., chromatography peak splitting).
                product_name:
                  type: string
                  description: The name of the product involved in the incident.
                test_name:
                  type: string
                  description: The name of the test being conducted.
                analyst:
                  type: string
                  description: Name of the analyst performing the test.
                instrument_name:
                  type: string
                  description: Name of the instrument used.
                instrument_number:
                  type: string
                  description: Identification number of the instrument.
                detail_visual_symptoms:
                  type: string
                  description: Detailed visual symptoms observed.
                description_of_incident:
                  type: string
                  description: A more detailed account of the incident.
                immediate_actions:
                  type: string
                  description: Actions taken immediately after the incident occurred.
      responses:
        '200':
          description: A list of investigation questions for the provided event.
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_description:
                    type: string
                    example: "chromatography peak splitting"
                  questions:
                    type: array
                    items:
                      type: string
                    example:
                      - "Was the analytical column recently replaced or maintained?"
                      - "Is the sample solvent compatible with the mobile phase?"
                      - "Has the system been checked for obstructions in the column?"
        '400':
          description: Invalid input data.
  
  /probable_root_causes:
    get:
      summary: Get probable root causes based on answered questions
      description: This endpoint accepts the answers to investigation questions and returns a list of probable root causes with details and corrective actions.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                questions:
                  type: array
                  description: Array of questions answered by the analyst.
                  items:
                    type: string
                  example:
                    - "Was the analytical column recently replaced or maintained?"
                    - "Is the sample solvent compatible with the mobile phase?"
                answers:
                  type: array
                  description: Corresponding answers for each question.
                  items:
                    type: string
                    enum: [yes, no, maybe]
                  example:
                    - yes
                    - maybe
      responses:
        '200':
          description: A list of probable root causes and their corrective actions (CAPA).
          content:
            application/json:
              schema:
                type: object
                properties:
                  probable_root_cause:
                    type: array
                    items:
                      type: object
                      properties:
                        cause:
                          type: string
                          example: "Column Overloading"
                        details:
                          type: string
                          example: "Excess sample injected leading to overloading of the HPLC column, causing peak splitting."
                        capa:
                          type: string
                          example: "Reduce sample volume or concentration to prevent column overloading."
        '400':
          description: Invalid input data.
